import localFont from "next/font/local";
import "./globals.css";
import { Prompt } from '@next/font/google'

const prompt = Prompt({
  subsets: ['latin'], // adjust as per your use case
  weight: ['400', '500', '700','900'], // select specific weights
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={prompt.className}>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
